# Generated by Django 4.1.2 on 2022-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=200)),
                ('nombre_autor', models.CharField(max_length=200)),
                ('titulo_libro', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('descripcion', models.TextField()),
                ('edad', models.PositiveIntegerField(default=0)),
                ('ciudad', models.CharField(max_length=200)),
                ('idioma', models.CharField(max_length=200)),
                ('numero_paginas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
